name: raypy310
channels:
  - pypi
  - r
  - defaults
  - conda-forge
dependencies:
  - abseil-cpp=20211102.0=h0e60522_0
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiofiles=22.1.0=py310haa95532_0
  - aiohttp=3.8.1=py310he2412df_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - aiosqlite=0.18.0=py310haa95532_0
  - anyio=3.5.0=py310haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py310haa95532_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py310he2412df_1004
  - bzip2=1.0.8=he774522_0
  - c-ares=1.19.0=h2bbff1b_0
  - ca-certificates=2023.08.22=haa95532_0
  - cachetools=5.3.0=pyhd8ed1ab_0
  - cffi=1.15.1=py310hcbf9ad4_0
  - click=8.1.3=py310h5588dad_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py310haa95532_0
  - cryptography=3.4.8=py310ha857299_1
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py310haa95532_0
  - exceptiongroup=1.0.4=py310haa95532_0
  - frozenlist=1.3.3=py310h2bbff1b_0
  - google-auth=2.19.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=hf108199_0
  - icu=73.1=h6c2663c_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - intel-openmp=2023.1.0=h57928b3_46319
  - ipykernel=6.25.0=py310h9909e9c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py310haa95532_0
  - jinja2=3.1.2=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema-specifications=2023.7.1=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter_client=7.4.9=py310haa95532_0
  - jupyter_console=6.6.3=py310haa95532_0
  - jupyter_core=5.5.0=py310haa95532_0
  - jupyter_events=0.6.3=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyter_server_fileid=0.9.0=py310haa95532_0
  - jupyter_server_ydoc=0.8.0=py310haa95532_1
  - jupyter_ydoc=0.2.4=py310haa95532_0
  - jupyterlab=3.6.3=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py310haa95532_0
  - jupyterlab_widgets=3.0.5=py310haa95532_0
  - krb5=1.20.1=h5b6d351_1
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libffi=3.4.4=hd77b12b_0
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=hb652d5d_1
  - libprotobuf=3.20.3=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markdown=3.4.3=pyhd8ed1ab_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mistune=2.0.4=py310haa95532_0
  - mkl=2020.4=hb70f87d_311
  - multidict=6.0.2=py310h2bbff1b_0
  - nbclassic=0.5.5=py310haa95532_0
  - nbclient=0.8.0=py310haa95532_0
  - nbconvert=7.10.0=py310haa95532_0
  - nbformat=5.9.2=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - notebook=6.5.4=py310haa95532_1
  - notebook-shim=0.2.2=py310haa95532_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=h2bbff1b_0
  - packaging=23.1=py310haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - platformdirs=3.10.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protobuf=3.20.3=py310h5588dad_1
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=py310haa95532_1
  - pyjwt=2.7.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyqt=5.15.10=py310hd77b12b_0
  - pyqt5-sip=12.13.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310h5588dad_5
  - python=3.10.11=h966fe2a_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-json-logger=2.0.7=py310haa95532_0
  - python_abi=3.10=2_cp310
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywin32=305=py310h2bbff1b_0
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyzmq=23.2.0=py310hd77b12b_0
  - qt-main=5.15.2=he2df7e6_10
  - qtconsole=5.4.2=py310haa95532_0
  - qtpy=2.2.0=py310haa95532_0
  - re2=2022.04.01=h0e60522_0
  - referencing=0.30.2=py310haa95532_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py310haa95532_0
  - rfc3986-validator=0.1.1=py310haa95532_0
  - rpds-py=0.10.6=py310h062c2fa_0
  - rsa=4.9=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=66.0.0=py310haa95532_0
  - sip=6.7.12=py310hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py310haa95532_1
  - soupsieve=2.5=py310haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tensorboard=2.13.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h5588dad_0
  - terminado=0.17.1=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.12=h2bbff1b_0
  - tomli=2.0.1=py310haa95532_0
  - tornado=6.3.3=py310h2bbff1b_0
  - typing_extensions=4.6.2=pyha770c72_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.38.4=py310haa95532_0
  - widgetsnbextension=4.0.5=py310haa95532_0
  - win_inet_pton=1.1.0=py310h5588dad_5
  - winpty=0.4.3=4
  - xz=5.4.2=h8cc25b3_0
  - y-py=0.5.9=py310hb6bf4ef_0
  - yaml=0.2.5=he774522_0
  - yarl=1.7.2=py310he2412df_2
  - ypy-websocket=0.8.2=py310haa95532_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
    - appdirs==1.4.4
    - asttokens==2.2.1
    - bert-score==0.3.13
    - blis==0.7.9
    - catalogue==2.0.8
    - certifi==2023.5.7
    - charset-normalizer==2.1.1
    - confection==0.0.4
    - contextualspellcheck==0.4.4
    - contourpy==1.0.7
    - cycler==0.11.0
    - cymem==2.0.7
    - cython==3.0.5
    - datasets==2.13.1
    - dill==0.3.6
    - docker-pycreds==0.4.0
    - editdistance==0.6.2
    - executing==1.2.0
    - filelock==3.12.0
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - gensim==4.3.2
    - gitdb==4.0.10
    - gitpython==3.1.31
    - grpcio==1.51.3
    - huggingface-hub==0.16.4
    - inexactsearch==1.0.2
    - ipython==8.13.2
    - jedi==0.18.2
    - joblib==1.2.0
    - jsonlines==3.1.0
    - jsonschema==4.17.3
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.2
    - matplotlib==3.5.2
    - mdurl==0.1.2
    - mpmath==1.2.1
    - msgpack==1.0.5
    - mteb==1.0.2
    - multiprocess==0.70.14
    - murmurhash==1.0.9
    - networkx==3.0
    - nltk==3.8.1
    - numpy==1.26.1
    - pandas==2.0.1
    - pathtools==0.1.2
    - pathy==0.10.1
    - pillow==9.3.0
    - pip==23.3.1
    - preshed==3.0.8
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - pyarrow==11.0.0
    - pydantic==1.10.8
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pyspellchecker==0.6.2
    - pytz==2023.3
    - pyyaml==6.0
    - ray==3.0.0.dev0
    - regex==2023.5.5
    - rich==13.4.2
    - safetensors==0.3.1
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.26.0
    - setproctitle==1.3.2
    - silpa-common==0.3
    - smart-open==6.3.0
    - smmap==5.0.0
    - soundex==1.1.3
    - spacy==3.5.3
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - stack-data==0.6.2
    - sympy==1.11.1
    - tensorboardx==2.6
    - theano==1.0.5
    - thinc==8.1.10
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - torch==2.0.1+cu117
    - torchaudio==2.0.2+cu117
    - torchdata==0.6.1
    - torchtext==0.15.2
    - torchvision==0.15.2+cu117
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.31.0
    - typer==0.7.0
    - typing-extensions==4.4.0
    - tzdata==2023.3
    - urllib3==1.26.16
    - wandb==0.15.4
    - wasabi==1.1.1
    - wcwidth==0.2.6
    - xdg==6.0.0
    - xxhash==3.2.0
prefix: C:\Users\karim\.conda\envs\temp_venv

